import { describe, expect, it } from "vitest";

import { buildPasswordResetOtpEmail } from "@/services/email/password-reset-email";

/**
 * The password-reset email.
 *
 * Pinned because this is the one piece of the flow that leaves the building.
 * A mistake here is not a broken page someone reloads — it is a message in an
 * inbox, forwarded and archived, that cannot be taken back.
 */

const CODE = "482913";

const message = buildPasswordResetOtpEmail({
  to: "trader@example.com",
  code: CODE,
  expiresInLabel: "10 minutes",
});

describe("buildPasswordResetOtpEmail", () => {
  it("addresses the recipient and names the product in the subject", () => {
    expect(message.to).toBe("trader@example.com");
    expect(message.subject).toBe("Your STOCKX password reset code");
  });

  it("carries the code in both the HTML and the plain-text part", () => {
    // Some clients render only the text alternative; a code missing from it is
    // a dead email for those readers.
    expect(message.html).toContain(CODE);
    expect(message.text).toContain(CODE);
  });

  it("renders the code as text, not as an image", () => {
    // Images are blocked by default in most clients, and a code nobody can see
    // is a support ticket.
    expect(message.html).not.toMatch(/<img/i);
  });

  it("says where the code goes", () => {
    expect(message.html).toContain("password reset page");
    expect(message.text).toContain("password reset page");
  });

  it("states the expiry, single use, and the attempt limit", () => {
    for (const body of [message.html, message.text]) {
      expect(body).toContain("10 minutes");
      expect(body.toLowerCase()).toContain("once");
      expect(body.toLowerCase()).toContain("incorrect attempts");
    }
  });

  it("carries the STOCKX branding", () => {
    expect(message.html).toContain("STOCKX");
    // The brand accent from the app's own tokens, not an arbitrary colour.
    expect(message.html).toContain("#d4a65e");
  });

  it("tells a recipient who did not ask for it that they can ignore it", () => {
    for (const body of [message.html, message.text]) {
      expect(body).toContain("Didn't ask for this?");
      expect(body).toContain("your password will not");
    }
  });

  it("carries the anti-phishing notice", () => {
    for (const body of [message.html, message.text]) {
      expect(body).toContain("never email you asking for your password");
    }
  });

  it("discloses nothing about the account beyond the address it was sent to", () => {
    /*
      No name, no cash figure, no portfolio value, no ids. Email is unencrypted
      at rest in most inboxes and is forwarded without thought, so a reset
      message is not the place to restate what somebody owns.

      Checked by shape rather than by keyword: the standing disclaimer legitimately
      contains the word "balances", so what matters is that no *figure* and no
      identifier is present.
    */
    for (const body of [message.html, message.text]) {
      expect(body).not.toMatch(/₹/);
      // A cuid, which is what every id in this schema looks like.
      expect(body).not.toMatch(/c[a-z0-9]{24}/);
    }

    /*
      The figure check runs against the plain-text part only. The HTML carries
      the palette as hex, and `#09090a` is a run of digits no money regex can
      tell from an amount — asserting there would fail on the background colour
      rather than on anything about the account.
    */
    expect(message.text).not.toMatch(/\d[\d,]*\.\d{2}/);
    expect(message.text).not.toMatch(/\d{1,3}(,\d{2,3})+/);
    // The one number this email legitimately carries is the code itself.
    expect(message.text.replace(CODE, "")).not.toMatch(/\d{5,}/);
  });

  it("escapes interpolated values rather than writing them raw", () => {
    /*
      Every value reaching this template is generated by the application today,
      so nothing hostile gets in. Escaped anyway: the day any of it becomes
      user-supplied, this is the line that stops it becoming an HTML injection
      into everyone's inbox.
    */
    const hostile = buildPasswordResetOtpEmail({
      to: "trader@example.com",
      code: '"><script>alert(1)</script>',
      expiresInLabel: "10 minutes",
    });

    expect(hostile.html).not.toContain("<script>");
    expect(hostile.html).toContain("&lt;script&gt;");
  });

  it("sends a plain-text alternative that is not just stripped markup", () => {
    expect(message.text).not.toContain("<");
    expect(message.text.length).toBeGreaterThan(100);
  });
});
