"use client";

import { useEffect, useState } from "react";

import { Panel, PanelHeader } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { SkeletonRows } from "@/components/ui/skeleton";
import { cn } from "@/lib/cn";
import type { TradeReview } from "@/services/analysis/trade-analysis";
import { handleSessionExpiry } from "@/lib/session-expiry";

type Status = "idle" | "loading" | "ready" | "error";

const SECTIONS = [
  { key: "wentWell", title: "What went well", tone: "up" },
  { key: "couldImprove", title: "What could improve", tone: "accent" },
  { key: "riskObservations", title: "Risk", tone: "neutral" },
  { key: "behaviouralObservations", title: "Behaviour", tone: "neutral" },
] as const;

/**
 * Trade review.
 *
 * The provider that produced the review is named on the panel. A reader should
 * always know whether they are looking at deterministic rules or model output —
 * the two carry different weight, and hiding the difference would be the sort
 * of quiet overclaim this feature is meant to avoid.
 */
export function TradeReviewPanel({ tripId }: { tripId: string | null }) {
  const [review, setReview] = useState<TradeReview | null>(null);
  const [status, setStatus] = useState<Status>("idle");
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    if (!tripId) {
      setStatus("idle");
      setReview(null);
      return;
    }

    let cancelled = false;
    setStatus("loading");
    setMessage(null);

    void (async () => {
      try {
        const response = await fetch(`/api/analysis/${tripId}`, { cache: "no-store" });

        if (handleSessionExpiry(response)) return;
        const payload = (await response.json()) as { review?: TradeReview; message?: string };
        if (cancelled) return;

        if (!response.ok || !payload.review) {
          setStatus("error");
          setMessage(payload.message ?? "This trade could not be reviewed.");
          return;
        }

        setReview(payload.review);
        setStatus("ready");
      } catch {
        if (!cancelled) {
          setStatus("error");
          setMessage("Could not reach the review service.");
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [tripId]);

  if (status === "idle") return null;

  if (status === "loading") {
    return (
      <Panel>
        <PanelHeader title="Trade review" />
        <SkeletonRows rows={4} className="px-5 md:px-6" />
      </Panel>
    );
  }

  if (status === "error" || !review) {
    return (
      <Panel>
        <PanelHeader title="Trade review" />
        <EmptyState
          title="No review available"
          description={message ?? "This trade could not be reviewed."}
          className="py-10"
        />
      </Panel>
    );
  }

  return (
    <Panel>
      <PanelHeader
        title="Trade review"
        description="An educational reading of one completed trade"
        action={
          <span
            className="inline-flex items-center gap-2 rounded-full border border-line px-2.5 py-1 text-[0.625rem] uppercase tracking-[0.12em] text-ink-tertiary"
            title={
              review.source === "local"
                ? "Generated by deterministic rules from this trade's figures"
                : "Generated by a language model from this trade's figures"
            }
          >
            <span
              aria-hidden
              className={cn(
                "size-1.5 rounded-full",
                review.source === "local" ? "bg-flat" : "bg-accent",
              )}
            />
            {review.source === "local" ? "Rule-based" : "Model"}
          </span>
        }
      />

      <div className="border-b border-line-subtle px-5 py-5 md:px-6">
        <p className="text-[0.9375rem] leading-relaxed text-ink">{review.headline}</p>
      </div>

      <div className="grid gap-px bg-line md:grid-cols-2">
        {SECTIONS.map((section) => {
          const items = review[section.key];
          if (items.length === 0) return null;

          return (
            <div key={section.key} className="bg-base px-5 py-5 md:px-6">
              <h3 className="eyebrow flex items-center gap-2">
                <span
                  aria-hidden
                  className={cn(
                    "size-1.5 rounded-full",
                    section.tone === "up" && "bg-up",
                    section.tone === "accent" && "bg-accent",
                    section.tone === "neutral" && "bg-ink-tertiary",
                  )}
                />
                {section.title}
              </h3>

              <ul className="mt-4 space-y-3">
                {items.map((item, index) => (
                  <li
                    key={index}
                    className="text-[0.8125rem] leading-relaxed text-ink-secondary"
                  >
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          );
        })}
      </div>

      <p className="border-t border-line-subtle px-5 py-4 text-xs leading-relaxed text-ink-tertiary md:px-6">
        {review.disclaimer}
      </p>
    </Panel>
  );
}
