/**
 * Trade analysis contract.
 *
 * Mirrors the market-data architecture: application code depends on
 * `TradeAnalysisProvider`, and the concrete provider is chosen in one place.
 * The local provider is the default and is fully featured — an absent API key
 * degrades *nothing*, it simply means the review is generated by rules rather
 * than by a model.
 *
 * ── Grounding ──────────────────────────────────────────────────────────────
 *
 * Every provider is handed a `TradeFacts` object computed from the trade
 * record. Providers describe those facts; they do not invent new ones. That is
 * what keeps a generated review checkable against the trade it describes, and
 * it is the reason facts are extracted here rather than inside a provider.
 *
 * ── What a review may never say ────────────────────────────────────────────
 *
 * No prediction, no guarantee, no instruction. A review states what happened
 * and what the numbers were. Phrasing is enforced by test, not by convention.
 */

import type { Paise, PriceE4 } from "@/lib/money";
import { notional, percentChange, priceToRupees } from "@/lib/money";
import type { ReplayFrame, RoundTrip } from "@/services/replay/replay-engine";
import { holdExtremes } from "@/services/replay/replay-engine";

/**
 * Everything measurable about a completed trade.
 *
 * Deliberately all numbers — no prose. Prose is the provider's job.
 */
export interface TradeFacts {
  readonly symbol: string;
  readonly quantity: number;
  readonly entryPrice: PriceE4;
  readonly exitPrice: PriceE4 | null;
  readonly realisedPnl: Paise;
  readonly realisedPnlPercent: number;

  readonly holdMs: number;
  readonly cost: Paise;
  /** Position cost as a share of capital. */
  readonly exposurePercent: number;

  /** Best unrealised gain reached during the hold. */
  readonly maxFavourable: Paise;
  /** Worst unrealised loss endured during the hold. */
  readonly maxAdverse: Paise;
  /**
   * Share of the best available gain that was actually booked, as a percent.
   * Null when the trade never showed a gain, where the ratio is meaningless.
   */
  readonly captureRatio: number | null;

  /** Instrument's move across the whole replay window. */
  readonly marketMovePercent: number;
  /** Move from the exit to the end of the window; null when nothing follows. */
  readonly postExitMovePercent: number | null;

  readonly automated: boolean;
  readonly barsHeld: number;
}

export interface ReviewSection {
  readonly title: string;
  readonly items: readonly string[];
}

export interface TradeReview {
  /** Which provider produced this. Surfaced so the reader knows. */
  readonly source: "local" | "model";
  /** One-line summary of the trade. */
  readonly headline: string;
  readonly wentWell: readonly string[];
  readonly couldImprove: readonly string[];
  readonly riskObservations: readonly string[];
  readonly behaviouralObservations: readonly string[];
  /** Always present, always shown. */
  readonly disclaimer: string;
}

export interface TradeAnalysisProvider {
  readonly name: string;
  /** True when this provider can actually run. */
  readonly available: boolean;
  analyse(facts: TradeFacts): Promise<TradeReview>;
}

export const REVIEW_DISCLAIMER =
  "This review describes one completed paper trade using simulated prices. It is an educational observation of what happened, not financial advice, not a judgement of skill, and not a prediction of future results. A single trade is dominated by chance.";

/**
 * Extract the measurable facts of a trade from its round trip and replay frames.
 *
 * Pure. The frames supply what the trade record alone cannot: how far the
 * position ran in each direction while it was open, which is the difference
 * between "you made ₹2,000" and "you made ₹2,000 of an available ₹9,000".
 */
export function extractFacts(
  trip: RoundTrip,
  frames: readonly ReplayFrame[],
  capital: Paise,
): TradeFacts {
  const { bestUnrealised, worstUnrealised } = holdExtremes(frames);

  /*
    The best gain available must include what was actually booked.

    `holdExtremes` only measures bars where a position is open, and on the exit
    bar the position is already flat — so a trade closed at its peak would
    report a "best available" lower than its own result, and the review would
    claim something like "captured 200% of the available move". You cannot bank
    more than was available; taking the maximum of the two makes that true by
    construction.
  */
  const maxFavourable = (
    trip.realisedPnl > bestUnrealised ? trip.realisedPnl : bestUnrealised
  ) as Paise;

  const cost = notional(trip.averageEntry, trip.quantity);
  const holdMs = (trip.closedAt ?? trip.openedAt) - trip.openedAt;

  const first = frames[0];
  const last = frames[frames.length - 1];

  const marketMovePercent =
    first && last
      ? percentChange(priceToRupees(first.candle.close), priceToRupees(last.candle.close))
      : 0;

  // How the instrument moved after the position was closed — the fact behind
  // "left on the table" or "exited before a reversal".
  const exitFrameIndex = frames.findIndex((frame) =>
    frame.events.some((event) => event.side === "SELL" && frame.position === 0),
  );

  const postExitMovePercent =
    exitFrameIndex >= 0 && last && exitFrameIndex < frames.length - 1
      ? percentChange(
          priceToRupees(frames[exitFrameIndex]!.candle.close),
          priceToRupees(last.candle.close),
        )
      : null;

  return {
    symbol: trip.symbol,
    quantity: trip.quantity,
    entryPrice: trip.averageEntry,
    exitPrice: trip.averageExit,
    realisedPnl: trip.realisedPnl,
    realisedPnlPercent: trip.realisedPnlPercent,
    holdMs,
    cost,
    exposurePercent: capital === 0 ? 0 : (cost / capital) * 100,
    maxFavourable,
    maxAdverse: worstUnrealised,
    captureRatio: maxFavourable <= 0 ? null : (trip.realisedPnl / maxFavourable) * 100,
    marketMovePercent,
    postExitMovePercent,
    automated: trip.automated,
    barsHeld: frames.filter((frame) => frame.position > 0).length,
  };
}

/** Unrealised drawdown endured as a share of the position's cost. */
export function adverseExcursionPercent(facts: TradeFacts): number {
  if (facts.cost === 0) return 0;
  return (Math.abs(facts.maxAdverse) / facts.cost) * 100;
}
