import type { QuoteSource } from "@/domain/market";
import { publicEnv } from "@/config/env";
import { cn } from "@/lib/cn";

/**
 * Where the prices on screen are actually coming from.
 *
 * Screens used to hard-code `source="simulated"`, which was true while the
 * simulator was the only provider and became a lie the moment live mode was
 * switched on: real Upstox prices carried a "Simulated data" badge. Reading
 * the mode means the badge cannot disagree with the provider.
 */
export function activeQuoteSource(): QuoteSource {
  return publicEnv.marketDataMode === "live" ? "live" : "simulated";
}

const LABEL: Record<QuoteSource, string> = {
  simulated: "Simulated data",
  live: "Live market data",
  historical: "Historical data",
};

const DETAIL: Record<QuoteSource, string> = {
  simulated: "Prices on this screen are generated by a local simulator. They are not real market prices.",
  live: "Prices are sourced from a live market data provider.",
  historical: "Prices are replayed from a historical record.",
};

/**
 * Provenance badge. Any surface showing prices must render one of these — a
 * user should never have to guess whether a number came from the real market.
 */
export function DataSourceBadge({
  source,
  className,
}: {
  source: QuoteSource;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-2 rounded-full border border-line px-2.5 py-1",
        "text-[0.625rem] font-medium uppercase tracking-[0.14em] text-ink-tertiary",
        className,
      )}
      title={DETAIL[source]}
    >
      <span
        aria-hidden
        className={cn(
          "size-1.5 rounded-full",
          source === "live" ? "bg-up" : source === "historical" ? "bg-accent" : "bg-flat",
        )}
      />
      {LABEL[source]}
    </span>
  );
}

/** The persistent paper-trading disclosure. */
export function VirtualMoneyBadge({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-2 rounded-full border border-accent/40 bg-accent/8 px-3 py-1",
        "text-[0.625rem] font-medium uppercase tracking-[0.14em] text-accent",
        className,
      )}
    >
      Paper trading · Virtual money
    </span>
  );
}
